# Generated by Django 4.0 on 2022-01-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_navbar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='pageName',
            new_name='title',
        ),
    ]
