# Generated by Django 4.0 on 2022-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_pagename_navbar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_menu',
            fields=[
                ('m_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_menu_name', models.CharField(max_length=50)),
                ('m_menu_link', models.CharField(max_length=100)),
            ],
        ),
    ]
